name: Build Black City APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip project
        run: |
          unzip SAMP-Mobile-Launcher-RN-main.zip.zip
          # Папканың нақты атын анықтап, айнымалыға сақтау
          DIR=$(ls -d */ | grep -v '.github' | head -n 1 | sed 's/\///')
          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ${{ env.PROJECT_DIR }}
          yarn install

      - name: Build Android Debug
        run: |
          cd ${{ env.PROJECT_DIR }}/android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BlackCity-Launcher
          path: ${{ env.PROJECT_DIR }}/android/app/build/outputs/apk/debug/app-debug.apk
